### ISSUE TITLE
Error in the deployment step npm run deploy

### ISSUE THREAD

**Issue by ijazm** [blockapps/blockapps-ba#42]
while deploying the project that is npm run deploy. I am getting an error 
 1) Supply Chain Demo App - deploy contracts should upload the contracts:
 Error: 401, /bloc//contracts/compile, "<html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx/1.10.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blockapps-ba@1.0.0 deploy: `mocha server/dapp/dapp.deploy.js --config server/config/${SERVER:-localhost}.config.yaml -b && cp server/config/${SERVER:-localhost}.config.yaml ./config.yaml`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the blockapps-ba@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Git2Swarm** [comment]
I am also facing same issue.. any solution or workaround?

**Comment by Git2Swarm** [comment]
### compile: {
  "compileList": [
    {
      "searchable": [
        "Bid"
      ],
      "contractName": "Bid",
      "source": "//import \"../../common/ErrorCodes.sol\";\ncontract ErrorCodes {\n\n    enum ErrorCodes {\n        NULL,\n        SUCCESS,\n        ERROR,\n        NOT_FOUND,\n        EXISTS,\n        RECURSIVE,\n        INSUFFICIENT_BALANCE\n    }\n}\n\n\n//import \"./BidState.sol\";\ncontract BidState {\n\n    enum BidState {\n        NULL,\n        OPEN,\n        ACCEPTED,\n        REJECTED\n    }\n}\n\n\n\n/**\n * Bid data contract\n */\ncontract Bid is ErrorCodes, BidState {\n  // NOTE: members must be public to be indexed for search\n  uint public id;\n  string public name;\n  string public supplier;\n  uint public amount;\n  BidState public state;\n\n  function Bid(uint _id, string _name, string _supplier, uint _amount) {\n    id = _id;\n    name = _name;\n    supplier = _supplier;\n    amount = _amount;\n    state = BidState.OPEN;\n  }\n\n  function getState() returns (BidState) {\n    return state;\n  }\n\n  function setState(BidState _state) {\n    state = _state;\n  }\n\n  function setBidState(BidState newState) returns (ErrorCodes) {\n    if (state == BidState.OPEN  &&  newState == BidState.ACCEPTED) {\n      setState(newState);\n      return ErrorCodes.SUCCESS;\n    }\n    if (state == BidState.OPEN  &&  newState == BidState.REJECTED) {\n      setState(newState);\n      return ErrorCodes.SUCCESS;\n    }\n    return ErrorCodes.ERROR;\n  }\n\n  function settle(address supplierAddress) returns (ErrorCodes) {\n    // confirm balance, to return error\n    if (this.balance < amount) {\n      return ErrorCodes.INSUFFICIENT_BALANCE;\n    }\n    uint fee = 10000000 wei; // supplier absorbs the fee\n    uint amountWei = amount * 1 ether;\n\n    // transfer will throw\n    supplierAddress.send(amountWei-fee);\n    return ErrorCodes.SUCCESS;\n  }\n}\n\n"
    }
  ]

**Comment by samrit** [comment]
We recently updated our getting started repo to the latest Bloc 2.1 API. This has broken some functionality with this demo app. We are upgrading the demo app to use the latest API and will be pushing a fix soon. Sorry for the inconvenience.

**Comment by samrit** [comment]
We have upraded the demo app to use the latest version of our API. You might have to nuke your node_modules folder and do the npm installs again to get the latest correct dependencies. Marking this issue as resolved.
