### ISSUE TITLE
npm run deploy is failing

### ISSUE THREAD

**Issue by sjeeva** [blockapps/blockapps-ba#45]
### createUser: {
  "name": "Admin_8199_887797964",
  "password": "1234"
}
    1) should upload the contracts

  0 passing (5m)
  1 failing

  1) Supply Chain Demo App - deploy contracts should upload the contracts:
     Error: 504, /bloc/v2.1/users/Admin_8199_887797964?faucet, "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.10.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"
      at node_modules/blockapps-rest/lib/rest_2_1.js:32:14

npm ERR! Linux 4.4.0-1013-aws
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "deploy"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! blockapps-ba@1.0.0 deploy: `mocha server/dapp/dapp.deploy.js --config server/config/${SERVER:-localhost}.config.yaml -b && cp server/config/${SERVER:-localhost}.config.yaml ./config.yaml`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the blockapps-ba@1.0.0 deploy script 'mocha server/dapp/dapp.deploy.js --config server/config/${SERVER:-localhost}.config.yaml -b && cp server/config/${SERVER:-localhost}.config.yaml ./config.yaml'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the blockapps-ba package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha server/dapp/dapp.deploy.js --config server/config/${SERVER:-localhost}.config.yaml -b && cp server/config/${SERVER:-localhost}.config.yaml ./config.yaml
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs blockapps-ba
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls blockapps-ba
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/blockapps-ba/npm-debug.log

**Comment by samrit** [comment]
@sjeeva it looks like your strato instance is not running. Can you try restarting/reinstalling your strato-getting-started instance.

**Comment by sjeeva** [comment]
@samrit, on a fresh setup I am not getting that error...
