### ISSUE TITLE
Logging into UI - What're the user passwords?

### ISSUE THREAD

**Issue by jkaczala** [blockapps/blockapps-ba#48]
Hi,

Apologies in advance if this is covered somewhere, but I haven't been able to find it.  

I was able to get the supply chain demo up and running, and started the UI at http://localhost:3030/login. I was also able to initiate tests so I now have 18 users to choose from, but I don't know what the default password is to log in with to play with the demo. I found the localhost.deploy.yaml and tried "1234" as the password but that doesn't seem to work.

Thanks in advance for your help!

-John

**Comment by samrit** [comment]
@jkaczala Sorry about that. The username and password to login to the UI have been added to the readme. They are `Buyer1`, `Buyer2`, `Supplier1`, `Supplier2` and the password is `1234` for all of them.
